package com.DPRIHKAT.entity.enums;

public enum TypeControle {
    VERIFICATION_DECLARATION,
    VERIFICATION_PAIEMENT,
    VERIFICATION_CONCESSION,
    VERIFICATION_PROPRIETE,
    VERIFICATION_VEHICULE
}
